# Generated by Django 4.2.11 on 2024-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mx', 'Mx')], max_length=10, null=True)),
                ('department', models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Business', 'Business'), ('Family and Consumer Sciences', 'Family and Consumer Sciences'), ('Social Studies', 'Social Studies'), ('Science', 'Science'), ('Foreign Language', 'Foreign Language'), ('Physical Education', 'Physical Education')], max_length=30, null=True)),
            ],
        ),
    ]
