# Generated by Django 4.2.11 on 2024-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0003_alter_student_first_name_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilepicture',
            name='alt',
            field=models.CharField(default='Profile Picture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilepicture',
            name='picture',
            field=models.ImageField(default='profiles/default.svg', upload_to='static/profiles/'),
        ),
    ]
